<a href="https://colab.research.google.com/github/SHAFIQUEKHANZADA/mastering-data-science/blob/main/NumPy/Phase_1_Numpy_Foundation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Phase 1 - Numpy Foundation**

# 🔢 Introduction to NumPy

**NumPy** (short for **Numerical Python**) is a powerful open-source library in Python that provides support for:

- **Multidimensional arrays** (also known as tensors)
- **Mathematical functions** to operate on these arrays
- **Efficient numerical computations**

---

## 🧠 Why Use NumPy?

- **Performance**: NumPy arrays are more efficient than Python lists for numerical operations.
- **Functionality**: It offers a wide range of mathematical functions, including linear algebra, statistics, and more.
- **Integration**: NumPy integrates well with other libraries like Pandas, Matplotlib, and SciPy.

---

## 🔍 Key Features

- **ndarray**: A fast and space-efficient multidimensional array object.
- **Broadcasting**: Perform arithmetic operations on arrays of different shapes.
- **Vectorization**: Eliminate the need for explicit loops, leading to cleaner and faster code.

---

## 📘 Example

In [1]:
import numpy as np

In [ ]:
# Create a 1D array
arr = np.array([1, 2, 3, 4, 5])

# Perform a vectorized operation
squared = arr ** 2

print("Original array:", arr)
print("Squared array:", squared)


Original array: [1 2 3 4 5]
Squared array: [ 1  4  9 16 25]


# NumPy Arrays vs. Python Lists

| Feature               | Python List                         | NumPy Array                          |
|-----------------------|-------------------------------------|--------------------------------------|
| **Data Type**         | Heterogeneous (mixed types allowed) | Homogeneous (single data type)       |
| **Performance**       | Slower for numerical computations   | Faster due to optimized C backend    |
| **Memory Efficiency** | Less efficient                      | More efficient                       |
| **Functionality**     | Basic operations                    | Advanced mathematical operations     |
| **Flexibility**       | Dynamic resizing and mixed types    | Fixed size and data type             |

**Key Takeaways:**
- Use **Python lists** for general-purpose programming where flexibility is needed.
- Use **NumPy arrays** for numerical computations and data analysis tasks for better performance and functionality.


In [ ]:
# python list multiplication
lists = [1,2,3]
print("Multiply List by 2: ", lists * 2)

# numpy array multiplication
arr = np.array([1,2,3])
print("Multiply Array by 2: ", arr * 2)

Multiply List by 2:  [1, 2, 3, 1, 2, 3]
Multiply Array by 2:  [2 4 6]


In [ ]:
# Let's check the time of both operations

import time

start = time.time()
py_list = [i*2 for i in range(100000)]
print("Python List operation time: ", time.time() - start)

start = time.time()
np_arr = np.arange(100000) * 2
print("NumPy Array operation time: ", time.time() - start)

Python List operation time:  0.0069124698638916016
NumPy Array operation time:  0.010230302810668945


# Creating Array from Scratch

In [ ]:
zeros_arr = np.zeros((3, 5)) # rows x colunms
print("Zeros Array:\n", zeros_arr)

onces_arr = np.ones((3, 5))
print("Onces Array:\n", onces_arr)

full_arr = np.full((3, 5), 7)
print("Full Array:\n", full_arr)

random_arr = np.random.random((3, 2))
print("Random Array:\n", random_arr)

sequence = np.arange(0, 31, 3)
print("Sequence Array:\n", sequence)

Zeros Array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Onces Array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Full Array:
 [[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]
Random Array:
 [[0.073961   0.87672446]
 [0.47552497 0.68226432]
 [0.02368707 0.0210119 ]]
Sequence Array:
 [ 0  3  6  9 12 15 18 21 24 27 30]


# Vector, Metrics and Tensors

In [ ]:
vector = np.array([1,2,3])
print("Vector: ", vector)

matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("Matrix: \n", matrix)

tensor = np.array([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[1,2,3], [4,5,6], [7,8,9]]
    ])
print("Tensor: \n", tensor)

Vector:  [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tensor: 
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


# Array properties

In [ ]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("Data Type: ", arr.dtype)

Shape:  (3, 3)
Dimension:  2
Size:  9
Data Type:  int64


# Array Reshaping

In [ ]:
arr = np.arange(1, 13)
print("Orignal array: ", arr)

reshaped = arr.reshape(3, 4)
print("Reshaped array: \n", reshaped)

flatended = reshaped.flatten()
print("Flatended array: ", flatended)

# ravel returns "view", instead of "copy"
raveled = reshaped.ravel()
print("Raveled array: ", raveled)

transposed = reshaped.T
print("Transposed array: \n", transposed)

Orignal array:  [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flatended array:  [ 1  2  3  4  5  6  7  8  9 10 11 12]
Raveled array:  [ 1  2  3  4  5  6  7  8  9 10 11 12]
Transposed array: 
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
