<a href="https://colab.research.google.com/github/SHAFIQUEKHANZADA/mastering-data-science/blob/main/NumPy/Phase_2_Operations_on_numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Phase 2 - Operations on numpy array**

In [1]:
import numpy as np

## 🔹 1D Array Slicing

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print("Baisc Slicing: ", arr[2:6])
print("Step Slicing: ", arr[1:9:2])
print("Reverse Slicing: ", arr[-1])

Baisc Slicing:  [3 4 5 6]
Step Slicing:  [2 4 6 8]
Reverse Slicing:  10


In [3]:
arr_2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print("Specific Elements", arr_2d[1,2])
print("Specific Row", arr_2d[1])
print("Specific Column", arr_2d[:,1])

Specific Elements 6
Specific Row [4 5 6]
Specific Column [2 5 8]


## Sorting

In [4]:
unsorted_arr = np.array([1,2,4,8,3,6,4,1])
print("Unsorted Array: ", unsorted_arr)

sorted_arr = np.sort(unsorted_arr)
print("Sorted Array: ", sorted_arr)

unsorted_2d = np.array([[3,1,2],
                        [6,4,5],
                        [6,0,9]])
print("2D Array sorted by column", np.sort(unsorted_2d, axis=0))
print("2D Array sorted by row", np.sort(unsorted_2d, axis=1))

Unsorted Array:  [1 2 4 8 3 6 4 1]
Sorted Array:  [1 1 2 3 4 4 6 8]
2D Array sorted by column [[3 0 2]
 [6 1 5]
 [6 4 9]]
2D Array sorted by row [[1 2 3]
 [4 5 6]
 [0 6 9]]


## Filter

In [5]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

even_number = numbers % 2 == 0
print("Even Numbers: ", numbers[even_number])

Even Numbers:  [ 2  4  6  8 10]


## Filter with mask

In [6]:
mask = numbers > 5

print("Numbers is grater than Five: ", numbers[mask])

Numbers is grater than Five:  [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [7]:
indices = [0,3,6]
print(numbers[indices])

where_result = np.where(numbers > 5, numbers * 3, "False")
print(where_result)

[1 4 7]
['False' 'False' 'False' 'False' 'False' '18' '21' '24' '27' '30']


## Adding and Removing Data

In [8]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1, arr2))
print("Combined Array: ", combined)

Combined Array:  [1 2 3 4 5 6]


## Array Compatibility

In [9]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatibility Shaps:", a.shape == b.shape)

Compatibility Shaps: True


In [10]:
orignal = np.array([[1,2], [3,4]])
new_row = np.array([5,6])

# Adding new row
combined = np.vstack((orignal, new_row))
print("Adding New Row: \n", combined)

# Adding new column
new_column = np.array([[7], [8]])
combined = np.hstack((orignal, new_column))
print("Adding New Column: \n", combined)

Adding New Row: 
 [[1 2]
 [3 4]
 [5 6]]
Adding New Column: 
 [[1 2 7]
 [3 4 8]]


In [11]:
arr = np.arange(1, 21)
print(arr)

deleted = np.delete(arr, [2, 18, 4])
print(deleted)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  2  4  6  7  8  9 10 11 12 13 14 15 16 17 18 20]
